### ISSUE TITLE
Rename to "Getting Started"

### ISSUE THREAD

**Issue by warpech** [Polyjuice/Welcome#2]
Today me, @andwah and @miyconst discussed potential name change for this app. "Getting Started" sounds good. @miyconst suggested that the priority for launchpad and menu can be controlled to put this app as the first one.

**Comment by miyconst** [comment]
How about these icons?

![welcome-1](https://cloud.githubusercontent.com/assets/6435556/9305086/f4d32392-44f6-11e5-88a8-33117645673d.png)
![welcome-2](https://cloud.githubusercontent.com/assets/6435556/9305085/f4d31f64-44f6-11e5-98e0-08eedf3cf45f.png)

**Comment by miyconst** [comment]
The new look:

![image](https://cloud.githubusercontent.com/assets/6435556/9306476/3d981934-4501-11e5-8ba6-2b7de9560366.png)

**Comment by miyconst** [comment]
The playgrounds not yet updated, need some confirmation before I update the playgrounds.

**Comment by warpech** [comment]
Closing (done)
